### PR TITLE
feat: lualine theme support

### PR DESCRIPTION
**Pull request by downzed**
I did try to do the minimalistic thing here, so let me know if that works.
I understand if it isn't because it's suitable for myself, but I thought it would be nice to share :)

### CODE REVIEW

**Comment by Aliqyan-21** [comment]
Looks good downzed, but I would suggest you to follow the proper structure of how we add plugin support in our darkvoid.nvim, as you can see in our plugins directory we have different files (gitsigns.lua, telescope.lua, etc. for the different plugins support in our theme.😁
config.lua then processes all these files and applies it in the colorscheme.
Thank You. Peace.

**Comment by downzed** [comment]
Will do. Cheers!

**Comment by Aliqyan-21** [comment]
Yes, downzed, the theme you proposed is good, maybe we will do some changes in the future in it, and for now I am merging your request and taking your complete colors for the lualine theme parsing it in our structure...Next time you yourself make it structured ok.

**Comment by downzed** [comment]
Oh, I was thinking about doing so myself.
But, thanks! I appreciate you merged it.

**Comment by Aliqyan-21** [comment]
Yes do check it out, does it look like you intended?
Check the configuration file to how to set up lualine.nvim for darkvoid.nvim

**Pull request merged**
